include ../make-lib/dirmathq.mk
include $(DIR_MATHQ)/make-lib/colors.mk
include $(DIR_MATHQ)/make-lib/core.mk
include $(DIR_MATHQ)/make-lib/infohelp.mk

EXEC += example

all: $(EXEC)

clean: cleanstd
	@\rm -f $(EXEC)


