include ../make-lib/dirmathq.mk
include $(DIR_MATHQ)/make-lib/style.mk
include $(DIR_MATHQ)/make-lib/core.mk
include $(DIR_MATHQ)/make-lib/infohelp.mk

EXEC += misctest Recurse ScalarTest ScalarTestComplex vtest mtest ttest


all: $(EXEC)

clean: cleanstd
	@\rm -f $(EXEC)


