#!/bin/bash
# ****  THIS WAS CREATED DURING  CONFIGURATION ******************
./printing
./testing
./testing2
./tfoverloading
./depth
./indexing
./imaginary
./enableexperiment
./selfmethod
./parmpack
