#!/bin/bash

pwd=`pwd`
echo -e "running deconfigure from pwd=${pwd}"
mydir=`dirname $(readlink -f $0)`
if [ "${pwd}" != "${mydir}" ]; then
    echo -e "${RED}ERROR${DEFCLR} You must run this script from its directory."
    exit -1
fi

source scripts/style.bash || exit 1

DIRMATHQ='make-lib/dirmathq.mk'

\make -j purge
\rm -f ${DIRMATHQ}

# the following are not removed by makefiles
\rm -fr examples/Makefile
\rm -fr scripts/__pycache__/

