#!/bin/bash


# TEXT ATTRIBUTES
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
GRAYlIGHT='\033[0;37m'
DEFCLR='\033[0;39m'
GRAYDARK='\033[0;90m'
REDLIGHT='\033[0;91m'
GREENLIGHT='\033[0;92m'
YELLOWLGIHT='\033[0;93m'
BLUELIGHT='\033[0;94m'
MAGNETALIGHT='\033[0;95m'
CYANLIGHT='\033[0;96m'
WHITE='\033[0;97m'

BOLDON='\e[0;1m'
BOLDOFF='\e[0;0m'

UNDERLINEON='\e[0;4m'
UNDERLINEOFF='\e[0;0m'



pwd=`pwd`
mydir=`dirname $(readlink -f $0)`
if [ "${pwd}" != "${mydir}" ]; then
    echo -e "${RED}ERROR${DEFCLR} You must run this script from its directory."
    exit -1
fi


if [ -e "Makefile" ]; then
    echo "deconfiguring..."
    make -j fullpurge
    rm -f Makefile{,.pristine}
    rm -f examples/Makefile{,.pristine}
else 
    echo "Nothing to do."
fi 




