

#prevent any default rules from being used
.SUFFIXES:

# don't delete .o files
.PRECIOUS: %.o


%.o: %.cpp 
ifdef CAREFUL
	$(CPP) $(CPPFLAGS) -D"MATRICKS_CAREFUL=1" -c $*.cpp -o $@
else
	$(CPP) $(CPPFLAGS) -c $*.cpp -o $@
endif


%: %.o 
	$(CPP) $(LDFLAGS) $*.o -o $@ $(LIBS) 


EXEC = example

all: $(EXEC)


clean:
	\rm -f *.o
	\rm -f $(EXEC)
	\rm -f core.*
	\rm -f *.s
	\rm -f *.temp

